const datas = {
  data: [
    {
      icon: "/images/facebook.png",
      name: "facebook",
      username: "nathanf",
      type: "followers",
      followers: 1987,
      growth: 12,
      isUp: true,
    },
    {
      icon: "/images/twitter.png",
      name: "twitter",
      username: "nathanf",
      type: "followers",
      followers: 1044,
      growth: 99,
      isUp: true,
    },
    {
      icon: "/images/instagram.png",
      name: "instagram",
      username: "realnathanf",
      type: "followers",
      followers: 11000,
      growth: 1099,
      isUp: true,
    },
    {
      icon: "/images/youtube.png",
      name: "youtube",
      username: "Nathan F.",
      type: "subscribers",
      followers: 8239,
      growth: 144,
      isUp: false,
    },
  ],
  overview: [
    {
      name: "facebook-views",
      icon: "/images/facebook.png",
      sectionName: "Page Views",
      isUp: true,
      count: 87,
      percentage: "3%",
    },
    {
      name: "facebook-likes",
      icon: "/images/facebook.png",
      isUp: true,
      sectionName: "Likes",
      count: 52,
      percentage: "2%",
    },
    {
      name: "instagram-likes",
      icon: "/images/instagram.png",
      isUp: true,
      sectionName: "Likes",
      count: 5462,
      percentage: "2257%",
    },
    {
      name: "instagram-views",
      icon: "/images/instagram.png",
      isUp: true,
      sectionName: "Profile Views",
      count: 52000,
      percentage: "1375%",
    },
    {
      name: "retweets",
      icon: "/images/twitter.png",
      isUp: true,
      sectionName: "Retweets",
      count: 117,
      percentage: "303%",
    },
    {
      name: "twitter-likes",
      icon: "/images/twitter.png",
      isUp: true,
      sectionName: "Likes",
      count: 507,
      percentage: "553%",
    },
    {
      name: "youtube-likes",
      icon: "/images/youtube.png",
      isUp: false,
      sectionName: "Likes",
      count: 107,
      percentage: "19%",
    },
    {
      name: "youtube-views",
      icon: "/images/youtube.png",
      isUp: false,
      sectionName: "Total Views",
      count: 1407,
      percentage: "12%",
    },
  ],
};

export default datas;
